version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/var/www/html

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - app
    environment:
      PHP_HOST: app

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  memcached:
    image: memcached:1.6

volumes:
  mysql:
