version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html

  web:
    build:
      context: ./docker/nginx
    ports:
      - 8000:80
    depends_on:
      - app
    environment:
      PHP_HOST: app

  db:
    build:
      context: ./docker/mysql
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=laravel"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  memcached:
    image: memcached:1.6

volumes:
  mysql:
